jobs:
  build:
    runs-on: '${{ matrix.arch.runner }}'
    steps:
      - uses: 'actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10'
        with:
          persist-credentials: false
      - name: 'Configure'
        run: 'cmake -S . -B build -DBUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=Release -DCPACK_SYSTEM_NAME=${{ matrix.arch.cpack_system }}'
      - name: 'Build'
        run: 'cmake --build build --config Release'
      - name: 'Package'
        run: 'cmake --build build --config Release --target package'
      - name: 'Upload artifacts'
        uses: 'actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a'
        with:
          if-no-files-found: 'error'
          name: 'libtether-${{ matrix.arch.name }}'
          path: 'build/*.zip'
      - if: "${{ github.ref_type == 'tag' }}"
        name: 'Upload package to release'
        env:
          GH_TOKEN: '${{ github.token }}'
          TAG: '${{ github.ref_name }}'
        run: |
          gh release create "$TAG" --draft --generate-notes --title "$TAG" || true
          gh release upload "$TAG" build/*.zip --clobber
    strategy:
      fail-fast: false
      matrix:
        arch:
          - cpack_system: 'x86_64'
            name: 'x86_64'
            runner: 'macos-15-intel'
          - cpack_system: 'arm64'
            name: 'arm64'
            runner: 'macos-latest'
name: 'CMake'
'on':
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/cmake.yml'
      - 'CMakeLists.txt'
      - 'include/**'
      - 'src/**'
      - 'tools/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/cmake.yml'
      - 'CMakeLists.txt'
      - 'include/**'
      - 'src/**'
      - 'tools/**'
    tags:
      - 'v*.*.*'
permissions:
  contents: 'write'
