jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10'
        with:
          persist-credentials: false
      - name: 'Install cmocka'
        run: 'sudo apt-get update && sudo apt-get install --no-install-recommends -y libcmocka-dev'
      - name: 'Configure'
        run: 'cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_C_COMPILER=${{ matrix.compiler }}'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        run: 'ctest --test-dir build --output-on-failure'
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - 'clang'
          - 'gcc'
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/tests.yml'
      - 'CMakeLists.txt'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/tests.yml'
      - 'CMakeLists.txt'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
permissions:
  contents: 'read'
