jobs:
  coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0'
        with:
          persist-credentials: false
      - name: 'Install cmocka and lcov'
        run: 'sudo apt-get update && sudo apt-get install --no-install-recommends -y lcov libcmocka-dev'
      - name: 'Configure'
        run: 'cmake -S . -B build -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON -DCMAKE_C_COMPILER=gcc'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        run: 'ctest --test-dir build --output-on-failure'
      - name: 'Capture coverage'
        run: |
          lcov --capture --directory build --output-file coverage.lcov --ignore-errors mismatch,unused
          lcov --remove coverage.lcov '/usr/*' '*/tests/*' --output-file coverage.lcov --ignore-errors unused
      - name: 'Coveralls'
        uses: 'coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e'
        with:
          file: 'coverage.lcov'
          format: 'lcov'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0'
        with:
          persist-credentials: false
      - name: 'Install cmocka'
        run: 'sudo apt-get update && sudo apt-get install --no-install-recommends -y libcmocka-dev'
      - name: 'Configure'
        run: 'cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_C_COMPILER=${{ matrix.compiler }}'
      - name: 'Build'
        run: 'cmake --build build'
      - name: 'Test'
        run: 'ctest --test-dir build --output-on-failure'
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - 'clang'
          - 'gcc'
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/tests.yml'
      - 'CMakeLists.txt'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/tests.yml'
      - 'CMakeLists.txt'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
permissions:
  contents: 'read'
